services:
  library:
    container_name: library
    build:
      context: .
      dockerfile: ./docker/library/Dockerfile
    ports:
      - ${PORT}:${PORT}
    restart: always
    depends_on:
      - database
    volumes:
      - .:/app
      - library:/app/node_modules
    networks:
      - bridge
  database:
    container_name: database
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
volumes:
  db:
  library: